Primaria_Digital/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.main.views import HomeView

urlpatterns = [
    #   url(r'^$', views.home),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^usuarios/', include('apps.users.urls', namespace='users')),
    url(r'^escuelas/', include('apps.escuelas.urls', namespace='escuelas')),
    url(r'^acciones/', include('apps.acciones.urls', namespace='acciones')),
    url(r'^dispositivos/', include('apps.dispositivos.urls', namespace='dispositivos')),
    url(r'^admin/', admin.site.urls),
]

apps/dispositivos/urls.py
from django.conf.urls import url
from .views import DispositivosView
from .views import EscuelaDispositivosView
from .views import CreateAdm
from .views import DispositivoCreateView
from .views import NetbookCreateView

urlpatterns = [
    url(r'^alta/dispositivo/netbooks/(?P<id_adm>[0-9]+)/',
        NetbookCreateView.as_view(), name='alta_netbook'),
    url(r'^alta/dispositivo/(?P<id_adm>[0-9]+)-(?P<n_tipo>[0-9]+)/',
        DispositivoCreateView.as_view(), name='alta_dispositivo'),
    url(r'^alta/adm', CreateAdm.as_view(), name='alta_adm'),
    url(r'^lista/', DispositivosView.as_view(), name='lista'),
    url(r'^dispo_list/', EscuelaDispositivosView.as_view(),
        name='listado_disp'),
]

apps/dispositivos/models.py
from django.db import models
# Traemos el Modelo Escuela
from apps.escuelas.models import Escuela

class Adm(models.Model):

    escuela = models.OneToOneField(Escuela)
    anio_recepcion = models.DateField()

    class Meta:
        verbose_name = "Adm"
        verbose_name_plural = "Adms"

    def __str__(self):
        return "{} - {}".format(self.escuela.nombre, self.anio_recepcion)


class Dispositivo(models.Model):

    adm = models.ForeignKey(Adm)
    tipo = models.IntegerField()
    estado = models.IntegerField(default=1)
    n_m = models.IntegerField(null=True)
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    n_s = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "Dispositivo"
        verbose_name_plural = "Dispositivos"

    def __str__(self):
        return "{} - {}".format(self.adm.escuela.nombre,
                                self.get_tipo(self.tipo))

    def get_tipo(self, tipo):
        if tipo == 1:
            return "Servidor"
        if tipo == 2:
            return "Cañon"
        if tipo == 3:
            return "Impresora"
        if tipo == 4:
            return "Camara"
        if tipo == 5:
            return "Netbook"
        if tipo == 6:
            return "Monitor"
        if tipo == 7:
            return "Pizarra"

apps/dispositivos/forms.py
from django import forms
# Traemos modelo Dispositivo y Adm
from .models import Dispositivo, Adm

"""
CHOICES_ESTADO = (
    (1, 'Buen Estado'),
    (2, 'Esperando Servicio Tecnico'),
    (3, 'Roto'),
)
"""

class DispositivoUnicoForm(forms.ModelForm):
    class Meta:
        model = Dispositivo
        fields = ('adm', 'estado', 'tipo', 'n_m', 'marca', 'modelo', 'n_s')
        widgets = {
            'adm': forms.TextInput(attrs={
                'type': 'hidden'
            }),
            'tipo': forms.TextInput(attrs={
                'type': 'hidden'
            }),
            'n_m': forms.TextInput(attrs={
                'type': 'hidden'
            }),
            'estado': forms.TextInput(attrs={
                'type': 'hidden'
            }),
        }

    def clean_n_m(self):
        adm = self.cleaned_data['adm']
        n_m = self.cleaned_data['n_m']
        if Dispositivo.objects.filter(adm=adm, n_m=n_m).exists():
            raise forms.ValidationError(
                'El numero de maquina ingresado ya existe en el adm')
        else:
            return n_m


class NetbookForm(forms.ModelForm):
    class Meta:
        model = Dispositivo
        fields = ('adm', 'estado', 'tipo', 'n_m', 'marca', 'modelo', 'n_s')
        widgets = {
            'adm': forms.TextInput(attrs={
                'type': 'hidden'
            }),
            'tipo': forms.TextInput(attrs={
                'type': 'hidden'
            }),
            'estado': forms.TextInput(attrs={
                'type': 'hidden'
            }),
        }

    def clean_n_m(self):
        adm = self.cleaned_data['adm']
        n_m = self.cleaned_data['n_m']
        # Si existe un numero de m duplicado
        if Dispositivo.objects.filter(adm=adm, n_m=n_m).exists():
            raise forms.ValidationError(
                'El numero de maquina ingresado ya existe en el adm')
        else:
            return n_m


"""
from collections import Counter
class NetbookMasiveForm(forms.Form):
    adm = forms.CharField(widget=forms.TextInput(attrs={'type': 'hidden'}))
    marca = forms.CharField(max_length=30)
    modelo = forms.CharField(max_length=30)
    maquina1 = forms.CharField(max_length=40)
    maquina2 = forms.CharField(max_length=40)
    maquina3 = forms.CharField(max_length=40)
    maquina4 = forms.CharField(max_length=40)
    maquina5 = forms.CharField(max_length=40)
    maquina6 = forms.CharField(max_length=40)
    maquina7 = forms.CharField(max_length=40)
    maquina8 = forms.CharField(max_length=40)
    maquina9 = forms.CharField(max_length=40)
    maquina10 = forms.CharField(max_length=40)
    maquina11 = forms.CharField(max_length=40)
    maquina12 = forms.CharField(max_length=40)
    maquina13 = forms.CharField(max_length=40)
    maquina14 = forms.CharField(max_length=40)
    maquina15 = forms.CharField(max_length=40)
    maquina16 = forms.CharField(max_length=40)
    maquina17 = forms.CharField(max_length=40)
    maquina18 = forms.CharField(max_length=40)
    maquina19 = forms.CharField(max_length=40)
    maquina20 = forms.CharField(max_length=40)
    maquina21 = forms.CharField(max_length=40)
    maquina22 = forms.CharField(max_length=40)
    maquina23 = forms.CharField(max_length=40)
    maquina24 = forms.CharField(max_length=40)
    maquina25 = forms.CharField(max_length=40)
    maquina26 = forms.CharField(max_length=40)
    maquina27 = forms.CharField(max_length=40)
    maquina28 = forms.CharField(max_length=40)
    maquina29 = forms.CharField(max_length=40)
    maquina30 = forms.CharField(max_length=40)

    def clean(self):
        adm = self.cleaned_data['adm']
        data = self.cleaned_data  # Traigo todos los datos
        maquinas = [] # en esta lista guardo los numeros de serie de las maquinas
        for maquina in data.values():
            maquinas.append(maquina)  # Guardando maquinas
        # Si existen duplicados se agrega al valor k y luego
        duplicado = [k for k, v in Counter(maquinas).items() if v > 1]
        # a la variable duplicado
        if duplicado == []:  # si existe duplicado
            for maquina in maquinas:
                if Dispositivo.objects.filter(adm=adm, n_s=maquina).exists():
                    raise forms.ValidationError(
                        'El numero de serie ingresado ya existe en la BD')
                else:
                    return self.cleaned_data
        else:
            raise forms.ValidationError('Numero de serie ingresado duplicado')
"""

apps/dispositivos/views.py
# shortcuts para renderizar
from django.shortcuts import render
# Vistas genericas
from django.views.generic import TemplateView, View, FormView, CreateView
# Modelos utilizados
from apps.escuelas.models import Escuela
from .models import Adm, Dispositivo
# Para retornar una respuesta en tipo JSON , al usar AJAX
from django.http import JsonResponse
# Para resolver urls basados en nombre
from django.core.urlresolvers import reverse_lazy, reverse
# Necesario para renderizar un template con el contexto apropiado y que lo devuelva en
# string para enviarlo a traves de ajax.
from django.template.loader import render_to_string
# Clases Formularios
from .forms import DispositivoUnicoForm, NetbookForm
# Mixin para agregar funcionalidad a las vistas
# Es necesario estar logeado para acceder a esta vista.
from django.contrib.auth.mixins import LoginRequiredMixin


# VIEW CREATE DISPOSITIVOS
# Con esta vista cargamos todos los dispositivos unicos que existen en un ADM
class DispositivoCreateView(LoginRequiredMixin, FormView):
    model = Dispositivo
    template_name = "alta_dispositivo.html"
    form_class = DispositivoUnicoForm
    success_url = reverse_lazy('dispositivos:lista')
    login_url = reverse_lazy('users:login')

    # Recibimos las variables por parametro y la agregamos al conexto de la
    # vista.
    def get(self, request, *args, **kwargs):
        context = super(DispositivoCreateView, self).get_context_data(**kwargs)
        # se agrega el Adm al contexto
        context['adm'] = Adm.objects.get(id=context['id_adm'])
        # Agregamos el ADM al objeto DispositivoCreateView
        self.id_adm = context['id_adm']
        # Devolvemos la pagina con el contexto modificado
        return render(request, self.template_name, context)

    def form_valid(self, form):  # Una vez que el formulario es valido...
        form.save()  # Guardamos el objeto del formulario.
        # Retornamos el formulario vacio
        return super(DispositivoCreateView, self).form_valid(form)

# Vista para alta de netbooks
# Esta vista se encarga de dar de alta una netbook en un adm escolar.


class NetbookCreateView(LoginRequiredMixin, FormView):
    model = Dispositivo
    template_name = "alta_netbooks.html"
    form_class = NetbookForm
    success_url = reverse_lazy('dispositivos:lista')
    login_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        # Recibimos las variables por parametro y la agregamos al conexto de la
        # vista.
        # se agrega el Adm al contexto
        context = super(NetbookCreateView, self).get_context_data(**kwargs)
        # Agregamos el ADM al objeto DispositivoCreateView
        context['adm'] = Adm.objects.get(id=context['id_adm'])
        # Devolvemos la pagina con el contexto modificado
        self.id_adm = context['id_adm']
        return render(request, self.template_name, context)

    def form_valid(self, form):
        form.save()  # Se guarda el objeto.
        form = NetbookForm()  # Se crea un formulario nuevo vacio
        return super(NetbookCreateView, self).form_valid(form)

# Vista para Crear Adm para la escuela


class CreateAdm(LoginRequiredMixin, View):

    login_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        # Obtenemos el valor del id de la escuela a traves de GET que nos envia
        # AJAX
        id_escuela = request.GET['id_escuela']
        # Creamos la variable anio para generar el anio
        anio = '{}-01-01'.format(request.GET['anio_recepcion'])
        # Traemos el objeto Escuela al que va  a estar asociado el adm
        escuela = Escuela.objects.get(id=id_escuela)
        # Creamos el ADM
        adm = Adm.objects.create(
            escuela=escuela,
            anio_recepcion=anio)
        adm.save()  # Guardamos
        mensaje = {'exito': '¡Adm agregado con exito!'}
        # Se envia a la page como un adm agregado con exito
        return JsonResponse(mensaje)

# VIEW DISPOSITIVOS
# Vista Principal , se les envia todos los establecimientos.
# Habria que mostrar la data dependiendo el usuario


class DispositivosView(LoginRequiredMixin, TemplateView):
    template_name = "lista_dispositivos.html"
    login_url = reverse_lazy('users:login')

    # Modificamos el get_context_data para que agregue las escuelas en el
    # contexto
    def get_context_data(self, **kwargs):
        context = super(DispositivosView, self).get_context_data(**kwargs)
        context['escuelas'] = Escuela.objects.all()
        return context

# AJAX , se utiliza para renderizar la pagina que va a ser enviadar por HTML a la vista
# lista_dispositivos.html ya que esta posee el ajax


class EscuelaDispositivosView(LoginRequiredMixin, View):

    login_url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        # Buscamos la escuela
        escuela_elegida = Escuela.objects.get(id=request.GET['id_escuela'])
        # Variable de contexto vacia para llenar con los datos necesarios
        context = {}
        # SI el adm no existe entonces...
        if not Adm.objects.filter(escuela=escuela_elegida).exists():
            # Se agrega el valor False a una key adm del contexto a enviar.
            context['adm'] = False
        else:  # Sino
            # Traemos el Adm de la escuela
            adm = Adm.objects.get(escuela=escuela_elegida)
            # le agregamos True , mirar datos_dispositivos.html para entender
            context['adm'] = True
            # Si existe un servidor
            if Dispositivo.objects.filter(adm=adm, tipo=1).exists():
                # Pongo toda la data del servidor
                context['servidor'] = Dispositivo.objects.get(adm=adm, tipo=1)
            else:
                # Sino mando bandera de que no existe servidor para ese ADM
                context['servidor'] = False
            # Si existe una camara
            if Dispositivo.objects.filter(adm=adm, tipo=2).exists():
                # Pongo toda la data del camara
                context['camara'] = Dispositivo.objects.get(adm=adm, tipo=2)
                # Sino mando bandera de que no existe camara para ese ADM
            else:
                context['camara'] = False
                # Si existe un impresora
            if Dispositivo.objects.filter(adm=adm, tipo=3).exists():
                # Pongo toda la data del impresora
                context['impresora'] = Dispositivo.objects.get(adm=adm, tipo=3)
                # Sino mando bandera de que no existe impresora para ese ADM
            else:
                context['impresora'] = False
                # Si existe un cañon
            if Dispositivo.objects.filter(adm=adm, tipo=4).exists():
                # Pongo toda la data del cañon
                context['canon'] = Dispositivo.objects.get(adm=adm, tipo=4)
                # Sino mando bandera de que no existe cañon para ese ADM
            else:
                context['canon'] = False
                #Si existe un Monitor
            if Dispositivo.objects.filter(adm=adm, tipo=6).exists():
                # Pongo toda la data del Monitor
                context['monitor'] = Dispositivo.objects.get(adm=adm, tipo=6)
                # Sino mando bandera de que no existe Monitor para ese ADM
            else:
                context['monitor'] = False
            #Si existe un pizarra
            if Dispositivo.objects.filter(adm=adm, tipo=7).exists():
                # Pongo toda la data del pizarra
                context['pizarra'] = Dispositivo.objects.get(adm=adm, tipo=7)
                # Sino mando bandera de que no existe pizarra para ese ADM
            else:
                context['pizarra'] = False
            # Agregar al contexto las netbooks
            context['netbooks'] = Dispositivo.objects.filter(
                adm=adm, tipo=5).order_by('n_m')
            # Agregar al contexto el adm
            context['adm_id'] = adm
        # Todo lo resultante del contexto se envia al html para construir el html a enviar
        # por AJAX
        html = (render_to_string('datos_dispositivos.html', context))
        # Enviar como Json el html resultante.
        return JsonResponse({'html': html})


"""
class NetbookFormMassiveView(FormView):
    model = Dispositivo
    template_name = "alta_netbooks.html"
    form_class = NetbookMasiveForm
    success_url = reverse_lazy('dispositivos:lista')

    def get(self,request,*args,**kwargs):
        context = super(NetbookFormMassiveView,self).get_context_data(**kwargs)
        context['adm'] = Adm.objects.get(id=context['id_adm'])
        self.id_adm = context['id_adm']
        return render(request,self.template_name,context)

    def form_valid(self,form):
        form_content = form.cleaned_data
        modelo = form_content.pop('modelo')
        marca = form_content.pop('marca')
        adm = Adm.objects.get(id=form_content.pop('adm'))
        index = 1
        try:
            for netbook in form_content.values():
                Dispositivo.objects.create(adm = adm,tipo = 5,n_m = index,
                marca = marca,modelo = modelo,n_s = netbook)
                index += 1
        except IntegrityError:
            super(NetbookFormMassiveView,self).form_invalid(form)
        return super(NetbookFormMassiveView,self).form_valid(form)
"""

apps/dispositivos/templates/alta_adm.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
    Alta de ADM
{% endblock title %}

{% block content %}
    <h2>Alta de ADM Escolar</h2>
    <form method="POST">
        {% csrf_token %}
        <ul>
            {% for field in form %}
            <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </li>
            {% endfor %}


        <li><a class='btnvolver' href="#">Volver</a><input type="submit" value="Dar de alta ADM"></li>
        </ul>
    </form>
{% endblock content %}

apps/dispositivos/templates/alta_dispositivo.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
    Alta de Dispositivo
{% endblock title %}

{% block content %}
    {% if n_tipo == '1' %}
        <h2>Alta de Servidor</h2> 
    {% elif n_tipo == '2' %}
        <h2>Alta de Cañon</h2>        
    {% elif n_tipo == '3' %}
        <h2>Alta de Impresora</h2> 
    {% elif n_tipo == '6' %}
        <h2>Alta de Monitor</h2> 
    {% elif n_tipo == '7' %}
        <h2>Alta de Pizarra</h2>        
    {% else %}
        <h2>Alta de Camara</h2>        
    {% endif %}

    <form method="POST">

        {% csrf_token %}

        <ul>
            {% for field in form %}

            {% if field.name == 'adm' %}
                {{ field }}
            {% elif field.name == 'tipo' %}
                {{ field }}
            {% elif field.name == 'n_m' %}
                {{ field }}
            {% elif field.name == 'estado' %}
                {{ field }}
            {% else %}
                <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                </li>
            {% endif %}
            
            {% endfor %}    
        
        
        <li><a class='btnvolver' href="{% url 'dispositivos:lista' %}">Volver</a><input type="submit" value="Dar de alta Dispositivo"></li>
        </ul>
    </form>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var idAdm = {{ adm.id }};
        var n_tipo = {{ n_tipo }};
        var n_m = (idAdm * 100) + n_tipo;
        $('#id_adm').val(idAdm);
        $('#id_tipo').val(n_tipo);
        $('#id_n_m').val(n_m);
    </script>
    
{% endblock scripts %}

apps/dispositivos/templates/alta_netbooks.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
    Alta de Dispositivo
{% endblock title %}

{% block content %}
    <h2>Alta de Netbooks</h2>

    <form method="POST">
        {% csrf_token %}
        <ul>
            {% for field in form %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                </li>
            {% endif %}
            {% endfor %}
        <li><a class='btnvolver' href="{% url 'dispositivos:lista' %}">Volver</a><input type="submit" value="Dar de alta Netbook"></li>
        </ul>
    </form>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        var idAdm = {{ adm.id }} ;
        var n_tipo = 5;
        $('#id_adm').val(idAdm);
        $('#id_tipo').val(n_tipo);
    </script>
    
{% endblock scripts %}

apps/dispositivos/templates/datos_dispositivos.html
{% if adm %}

    <div id="data">
        <div class="container">
            <div class="panel">
            {% if servidor %}
                <div class="panel-header">Servidor</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ servidor.marca }} </div>
                    <div class='content'>Modelo: {{ servidor.modelo }} </div>
                    <div class='content'>N°S: {{ servidor.n_s }} </div>
                    {% if servidor.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif servidor.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                </div>
            {% else %}
                <div class="panel-header">Servidor</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra un servidor registrado</div>
                    <div class="content">¿Desea ingresar un servidor a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '1' %}">Añadir Servidor</a></div>
                </div>
            {% endif %}

            </div>
            <div class="panel">
            {% if canon %}
                <div class="panel-header">Cañon</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ canon.marca }}</div>
                    <div class='content'>Modelo: {{ canon.modelo }}</div>
                    <div class='content'>N°S:{{ canon.n_s }}</div>
                    {% if canon.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif canon.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                    
                </div>
            {% else %}
                <div class="panel-header">Cañon</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra un cañon registrado</div>
                    <div class="content">¿Desea ingresar un Cañon a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '2' %}">Añadir Cañon</a></div>
                </div>
                </div>
            {% endif %}

            </div>
        </div>
            <div class="panel">
            {% if impresora %}
                <div class="panel-header">Impresora</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ impresora.marca }}</div>
                    <div class='content'>Modelo: {{ impresora.modelo }}</div>
                    <div class='content'>N°S: {{ impresora.n_s }}</div>
                    {% if impresora.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif impresora.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                </div>
            {% else %}
                <div class="panel-header">Impresora</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra una impresora registrada</div>
                    <div class="content">¿Desea ingresar un Impresora a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '3' %}">Añadir Impresora</a></div>
                </div>
                </div>
            {% endif %}

            </div>
            <div class="panel">
            {% if camara %}
                <div class="panel-header">Camara</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ camara.marca }} </div>
                    <div class='content'>Modelo:{{ camara.modelo }} </div>
                    <div class='content'>N°S:{{ camara.n_s }}</div>
                    {% if camara.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif camara.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                </div>
            {% else %}
                <div class="panel-header">Camara</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra una camara registrada</div>
                    <div class="content">¿Desea ingresar un Camara a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '4' %}">Añadir Camara</a></div>
                </div>
                </div>
            {% endif %}
            </div>
            <div class="panel">
            {% if monitor %}
                <div class="panel-header">Monitor</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ monitor.marca }} </div>
                    <div class='content'>Modelo:{{ monitor.modelo }} </div>
                    <div class='content'>N°S:{{ monitor.n_s }}</div>
                    {% if monitor.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif monitor.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                </div>
            {% else %}
                <div class="panel-header">Monitor</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra una monitor registrada</div>
                    <div class="content">¿Desea ingresar un monitor a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '6' %}">Añadir monitor</a></div>
                </div>
                </div>
            {% endif %}
            </div>
            <div class="panel">
            {% if pizarra %}
                <div class="panel-header">Pizarra</div>
                <div class="panel-body">
                    <div class='content'>Marca: {{ pizarra.marca }} </div>
                    <div class='content'>Modelo:{{ pizarra.modelo }} </div>
                    <div class='content'>N°S:{{ pizarra.n_s }}</div>
                    {% if pizarra.estado == 1 %}
                        <div class='content'>Estado: Buen Estado</div>
                    {% elif pizarra.estado == 2 %}
                        <div class='content'>Estado: En espera de Servicio Tecnico</div>
                    {% else %}
                        <div class='content'>Estado: Roto</div>
                    {% endif %}
                </div>
            {% else %}
                <div class="panel-header">Pizarra</div>
                <div class="panel-body">
                    <div class='content'>No se encuentra una pizarra registrada</div>
                    <div class="content">¿Desea ingresar un pizarra a este ADM?</div>
                    <div class="content"><a class="actualizarbtn" href="{% url 'dispositivos:alta_dispositivo' adm_id.id '7' %}">Añadir Pizarra</a></div>
                </div>
                </div>
            {% endif %}
            </div>

            <a class="actualizarbtn" style='margin: 60px 30px' href="{% url 'dispositivos:alta_netbook' adm_id.id %}">Añadir Netbook</a>

        {% if netbooks %}
            <table class="netbooks">
                <thead class="table-header">
                    <tr>
                        <th class="row-id" style="padding:5px">#</th>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>N° de serie</th>
                        <th>Estado</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody class="table-body">
                    
                        {% for netbook in netbooks %}
                        <tr>
                        <td class="row-id" style="padding:5px">{{ netbook.n_m }}</td>
                        <td>{{ netbook.marca }}</td>
                        <td>{{ netbook.modelo }}</td>
                        <td>{{ netbook.n_s }}</td>
                        {% if netbook.estado == 1 %}
                            <td>Buen Estado</td>
                        {% elif netbook.estado == 2 %}
                            <td>Espera de servicio tecnico</td>
                        {% else %}
                            <td>Roto</td>
                        {% endif %}
                        <td></td>
                        </tr>    
                        {% endfor %}
                        
                </tbody>
            </table>
            {% else %}
             <table class="netbooks">
                <thead class="table-header">
                    <tr>
                       <th>No se encuentran netbooks registradas para este ADM</th>
                    </tr>
                </thead>
            </table>
        {% endif %}
    </div>    
        
                
{% else %}
    <form>
    <ul>
        <li>
            <p>La escuela seleccionada no tiene un adm registrado , ¿Desea registrarla?</p>
        </li>
        <li>
            <label for='#anio_recepcion'>Elija el año de recepcion</label>
            <select class='select-dispo' id='anio_recepcion'>
                <option value="2011">2011</option>
                <option value="2012">2012</option>
                <option value="2013">2013</option>
                <option value="2014">2014</option>
                <option value="2015">2015</option>
                <option value="2016">2016</option>
                <option value="2017">2017</option>
            </select>
        </li>
        <li>
            <button onclick="AltaAdm()" class='actualizarbtn'>Dar de alta ADM</button>
        </li>
    </ul>    
    </form>
    <script type="text/javascript">
    function AltaAdm(){
        var id_escuela = $("#escuela").val();
        var anio_recepcion = $("#anio_recepcion").val();
        $.ajax({

                data : { 'id_escuela' : id_escuela,
                         'anio_recepcion' : anio_recepcion},
                method : 'GET',
                url : '{% url "dispositivos:alta_adm" %}',
                datatype : 'json',
                success: function(data){
                    console.log(data)
                    mostrardatos()
                }
            })

    };
    </script>
{% endif %}