Primaria_Digital/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.main.views import HomeView

urlpatterns = [
    #   url(r'^$', views.home),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^usuarios/', include('apps.users.urls', namespace='users')),
    url(r'^escuelas/', include('apps.escuelas.urls', namespace='escuelas')),
    url(r'^acciones/', include('apps.acciones.urls', namespace='acciones')),
    url(r'^dispositivos/', include('apps.dispositivos.urls', namespace='dispositivos')),
    url(r'^admin/', admin.site.urls),
]

apps/acciones/urls.py
from django.conf.urls import url

from .views import AccionCreateView, AccionListView

urlpatterns = [
    url(r'^alta/', AccionCreateView.as_view(), name='alta'),
    url(r'^lista/', AccionListView.as_view(), name='lista'),
]

apps/acciones/models.py
from django.db import models
from apps.escuelas.models import Escuela
from django.contrib.auth.models import User

# Create your models here.
class Accion(models.Model):

    escuela = models.ForeignKey(Escuela)
    usuario = models.ForeignKey(User)
    accion = models.TextField()
    observaciones = models.TextField(null=True,default=None)
    fecha = models.DateTimeField()
    realizada = models.BooleanField(default=True)
    programada = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Accion"
        verbose_name_plural = "Acciones"

    def __str__(self):
        return "{} - {}".format(self.escuela,self.usuario)
    

apps/acciones/forms.py
from django import forms
from .models import Accion
from datetime import datetime

class AccionForm(forms.ModelForm):
    class Meta:
        model = Accion
        fields = ('escuela','accion','fecha',)
        widgets = {
        'escuela': forms.Select(attrs={
            'type':'textarea',
            }),
        'accion': forms.Textarea(attrs={
            'type':'textarea',
            'rows':'4',
             'cols':'50',
            }),
        }

    def clean(self,**kwargs):
        data = super(AccionForm,self).clean(**kwargs)
        return data

apps/acciones/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User

from .forms import AccionForm
from .models import Accion

# Create your views here.

class AccionCreateView(LoginRequiredMixin,CreateView):
    model = Accion
    template_name = "alta_accion.html"
    login_url = reverse_lazy('users:login')
    form_class = AccionForm
    success_url = reverse_lazy('acciones:lista')

    def form_valid(self,form):
        form.instance.usuario = self.request.user
        return super(AccionCreateView,self).form_valid(form)

class AccionListView(ListView):
    model = Accion
    template_name = "lista_acciones.html"

    def get_context_data(self,**kwargs):
        context = super(AccionListView,self).get_context_data(**kwargs)
        context['acciones'] = Accion.objects.filter(usuario = self.request.user)
        return context

apps/acciones/templates/alta_accion.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "css/jquery-ui.css" %} ">
    
{% endblock styles %}

{% block title %}
    Alta de Accion
{% endblock title %}

{% block content %}
    <h2>Alta de Accion</h2>
    <form method="POST">
        {% csrf_token %}
        <ul>
            
            {% for field in form %}
            <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </li>
            {% endfor %}   
            <li><input type="hidden" name='usuario_id' value='{{ user.id }}'></li> 
        
        
        <li><a class='btnvolver' href="{% url 'home' %} ">Volver</a><input type="submit" value="Ingresar Accion"></li>
        </ul>
    </form>
{% endblock content %}


{% block scripts %}
    {{ block.super }}
    <script type="text/javascript" src="{% static "js/jquery-ui.js" %}"></script>
    <script type="text/javascript">
        $("#id_fecha").datepicker({
            changeMonth: true,
            dateFormat: 'yy-mm-dd',
            appendText: 'yy/mm/dd'
        });
    </script>
{% endblock scripts %}

apps/acciones/templates/lista_acciones.html
{% extends "base.html" %}

{% load static from staticfiles %}
{% block title %}
    Alta de Accion
{% endblock title %}

{% block content %}
    <h2>Listado de tus Acciones</h2>
    <table>
        <thead>
            <tr>
                <th>Escuela</th>
                <th>Accion</th>
                <th>Fecha</th>
                <th>¿Realizada?</th>
            </tr>
        </thead>
        <tbody>
            {% for accion in acciones %}
             <tr>
                <td>{{ accion.escuela.nombre }}</td>
                <td>{{ accion.accion }}</td>
                <td>{{ accion.fecha }}</td>
                {% if accion.realizada %}
                    <td style="text-align: center"><span class="icon-checkmark"></span></td>    
                {% else %}
                    <td style="text-align: center"><span class="icon-cross"></span></td>
                {% endif %}
            </tr>     
            {% endfor %}
        </tbody>
        
    </table>
{% endblock content %}