Primaria_Digital/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.main.views import HomeView

urlpatterns = [
    #   url(r'^$', views.home),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^usuarios/', include('apps.users.urls', namespace='users')),
    url(r'^escuelas/', include('apps.escuelas.urls', namespace='escuelas')),
    url(r'^acciones/', include('apps.acciones.urls', namespace='acciones')),
    url(r'^dispositivos/', include('apps.dispositivos.urls', namespace='dispositivos')),
    url(r'^admin/', admin.site.urls),
]

apps/acciones/urls.py
from django.conf.urls import url

from .views import AccionCreateView, AccionListView

urlpatterns = [
    url(r'^alta/', AccionCreateView.as_view(), name='alta'),
    url(r'^lista/', AccionListView.as_view(), name='lista'),
]

apps/users/urls.py
from django.conf.urls import url
from .views import RegisterView, LoginView, LogoutView

urlpatterns = [
    url(r'^registrar/$',RegisterView.as_view() , name='register'),
    url(r'^login/',LoginView.as_view() , name='login'),
    url(r'^salir/$',LogoutView.as_view() , name='logout'),
]

apps/main/models.py
from django.db import models

# Create your models here.

apps/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"
    login_url = reverse_lazy('users:login')

apps/main/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title> {% block title %}
        
    {% endblock title %} </title>

    
    {% load static from staticfiles %}
    
    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static "css/general.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/header.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/form.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/icomoon.css" %} ">
    <link href="https://fonts.googleapis.com/css?family=Averia+Libre" rel="stylesheet"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% endblock styles %}
</head>


<body>
    <section id="contenedor">
        <header>
            <div id="head">
                <div id="titulo">
                <span class="logo"><img src="{% static "img/logo.png" %} "></span><a href="{% url 'home' %}"><h1>Bitacora del Capitan</h1></a>
                </div>
                {% include "navbar.html" %}
            </div>
        </header>

         <div id='cuerpo'>
             {% block content %}
                 
             {% endblock content %}
         </div>

         <footer>
            <div id="pie">
                <a id="logout" href="{% url 'users:logout' %}">Cerrar sesión</a>  
            </div>
        </footer>
    </section>


{% block scripts %}
    <script type="text/javascript" src="{% static "js/jquery-3.1.1.js" %}"></script>
{% endblock scripts %}
</body>

</html>

apps/main/templates/home.html
{% extends "base.html" %}

{% block title %}
    Home - Bitacora del Capitán
{% endblock title %}

{% load static from staticfiles %}

{% block content %}

    <h2>Bienvenido a la bitacora del capitan.</h2>
    <p>La idea de esta aplicacion web es poder mantener informacion con respecto a las acciones que se llevaran y llevan a cabo en las escuelas primarias.</p>
    
{% endblock content %}

apps/main/templates/navbar.html
<nav>
    <ul>
        {% if user.is_authenticated %}
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Escuelas</a>
                <div class="dropdown-content">
                    <a href="{% url 'escuelas:alta' %}">Añadir Escuela</a>
                    <a href="{% url 'escuelas:lista' %}">Listar Escuela</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Acciones</a>
                <div class="dropdown-content">
                    <a href="{% url 'acciones:alta' %}">Añadir Accion</a>
                    <a href="{% url 'acciones:lista' %}">Mis Acciones</a>
                </div>
            </li>
            
            <li><a href="{% url 'dispositivos:lista' %}">Dispositivos</a></li>
        {% endif %}
    </ul>
</nav>