Primaria_Digital/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from apps.main.views import HomeView

urlpatterns = [
    #   url(r'^$', views.home),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^usuarios/', include('apps.users.urls', namespace='users')),
    url(r'^escuelas/', include('apps.escuelas.urls', namespace='escuelas')),
    url(r'^acciones/', include('apps.acciones.urls', namespace='acciones')),
    url(r'^dispositivos/', include('apps.dispositivos.urls', namespace='dispositivos')),
    url(r'^admin/', admin.site.urls),
]

apps/escuelas/urls.py
from django.conf.urls import url
from .views import EscuelaCreateView,EscuelaUpdateView,ListaEscuelasView


urlpatterns = [
    url(r'^alta/$', EscuelaCreateView.as_view(), name='alta'),
    url(r'^modificar/(?P<pk>[0-9]+)/$', EscuelaUpdateView.as_view(), name='modificar'),
    url(r'^lista/$', ListaEscuelasView.as_view(), name='lista'),
]

apps/escuelas/models.py
from django.db import models

# Create your models here.

class Escuela(models.Model):

    nombre = models.CharField(max_length=80)
    cue = models.IntegerField()
    domicilio = models.CharField(max_length=80)
    telefono = models.CharField(max_length=50)
    directivo = models.CharField(max_length=50)
    tel_directivo = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Escuela"
        verbose_name_plural = "Escuelas"

    def __str__(self):
        return '{} - {}'.format(self.nombre, self.cue)
        #return "%s - %d" % (self.escuela,self.cue) 
     

apps/escuelas/forms.py
from django import forms
from .models import Escuela

class EscuelaForm(forms.ModelForm):
    class Meta:
        model = Escuela
        fields = ('nombre','cue','domicilio','telefono','directivo','tel_directivo')

    

apps/escuelas/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Escuela
from .forms import EscuelaForm

# Create your views here.
class EscuelaCreateView(LoginRequiredMixin,CreateView):
    model = Escuela
    template_name = "alta.html"
    form_class = EscuelaForm
    success_url = reverse_lazy('escuelas:lista')
    login_url = reverse_lazy('users:login')

class EscuelaUpdateView(LoginRequiredMixin,UpdateView):
    model = Escuela
    template_name = "modificacion.html"
    form_class = EscuelaForm
    success_url = reverse_lazy('escuelas:lista')
    login_url = reverse_lazy('users:login')

class ListaEscuelasView(LoginRequiredMixin,TemplateView):
    template_name = "listado_colegios.html"
    login_url = reverse_lazy('users:login')

    def get_context_data(self,**kwargs):
        context = super(ListaEscuelasView,self).get_context_data(**kwargs)
        context['escuelas'] = Escuela.objects.all()
        print(context['escuelas'])
        return context

apps/escuelas/templates/alta.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
    Alta de Escuela
{% endblock title %}

{% block content %}
    <h2>Alta de escuela</h2>
    <form method="POST">
        {% csrf_token %}
        <ul>
            {% for field in form %}
            <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </li>
            {% endfor %}    
        
        
        <li><a class='btnvolver' href="{% url 'escuelas:lista' %} ">Volver</a><input type="submit" value="Dar de alta escuela"></li>
        </ul>
    </form>
{% endblock content %}

apps/escuelas/templates/listado_colegios.html
{% extends "base.html" %}

{% block title %}
    Lista de Colegios
{% endblock title %}

{% block content %}
    <h2>Listado de colegios</h2>
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Cue</th>
                <th>Directivo</th>
                <th>Tel. Directivo</th>
                <th>Domicilio</th>
                <th>Telefono</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for escuela in escuelas %}
            <tr>
                <td>{{ escuela.nombre }}</td>
                <td>{{ escuela.cue }}</td>
                <td>{{ escuela.directivo }}</td>
                <td>{{ escuela.tel_directivo }}</td>
                <td>{{ escuela.domicilio }}</td>
                <td>{{ escuela.telefono }}</td>
                <td style="text-align: center"><a class='actualizarbtn' href="{% url 'escuelas:modificar' escuela.id %} ">Editar</a></td>
            </tr> 
            {% endfor %}
        </tbody>
        
    </table>
{% endblock content %}

apps/escuelas/templates/modificacion.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}
    Modificacion datos de Escuela {{ form.name.value }}
{% endblock title %}

{% block content %}
    
    <br><br>
    <h2>Alta de escuela</h2>    
    <form method="POST">
        {% csrf_token %}
        <ul>
            {% for field in form %}
            <li>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </li>
            {% endfor %}    
        
        
        <li><a class='btnvolver' href="{% url 'escuelas:lista' %} ">Volver</a><input type="submit" value="Modificar datos de la escuela"></li>
        </ul>
    </form>
    
{% endblock content %}